### ISSUE TITLE
Why using strings as symbols?

### ISSUE THREAD

**Issue by Ana06** [coolo/xmlhash#4]
Wouldn't it be more efficient to use symbols? :thinking: I mean you need to convert them, but it will save memory and time when accessing.

**Comment by coolo** [comment]
this would create a lof of symbols - and you would have to convert all of them to save time accessing one.

Feel free to benchmark.

**Comment by coolo** [comment]
(and avoid breaking all code acessing the hash with strings :)

**Comment by coolo** [comment]
(nokogori's to_hash outputs symbols btw)
